"""Trading strategy engine — evaluates holdings and generates trade signals.

Each security is assigned one of three strategy forks:
  1. CASH_OUT         — monitor for take-profit or trailing stop to reduce/exit position
  2. INCREASE_HOLDING — accumulate via DCA and buy-the-dip
  3. HOLD             — sit tight unless stop-loss triggers (avoid premature selling)

Buy signals are tagged with a BuyType (DCA or STRATEGY) so the guidelines
engine can enforce separate budgets for each.
"""

from dataclasses import dataclass
from datetime import datetime, date, timedelta
from typing import Optional

from .models import (
    BuyType,
    Holding,
    InvestmentGuidelines,
    OrderSide,
    Portfolio,
    StrategyMode,
    TradingStrategy,
)
from .guidelines import load_guidelines_with_spending
from .watermark import update_watermarks, DEFAULT_MAX_TICK_JUMP_PCT


@dataclass
class TradeSignal:
    """A proposed trade generated by the strategy engine."""
    symbol: str
    side: OrderSide
    quantity: float
    reason: str
    estimated_value: float
    strategy_mode: StrategyMode
    buy_type: BuyType = BuyType.STRATEGY   # DCA vs strategy-triggered
    priority: int = 0  # Higher = more urgent
    limit_price: Optional[float] = None   # Set for limit orders (e.g. buy-dip)

    def __str__(self):
        tag = f"[{self.buy_type.value.upper()}]" if self.side == OrderSide.BUY else ""
        return (
            f"  {'🔴' if self.side == OrderSide.SELL else '🟢'} "
            f"{self.side.value.upper()} {self.quantity:.4f} {self.symbol} "
            f"(~${self.estimated_value:,.2f}) — {self.reason} {tag}"
        )


class StrategyEngine:
    """Evaluates all holdings against their strategies and generates trade signals."""

    def __init__(self, portfolio: Portfolio, strategies: dict[str, TradingStrategy],
                 guidelines: InvestmentGuidelines, price_fetcher=None,
                 last_dca_dates: dict[str, date] = None,
                 persist_watermarks: bool = False,
                 watermark_max_jump_pct: float = DEFAULT_MAX_TICK_JUMP_PCT):
        self.portfolio = portfolio
        self.strategies = strategies
        self.guidelines = load_guidelines_with_spending(guidelines)
        self.price_fetcher = price_fetcher  # callable(symbol) -> float
        self.last_dca_dates = last_dca_dates  # symbol → last DCA execution date
        # Only the trading loop persists peaks; preview paths (dashboard, CLI
        # signals) leave this False so viewing never mutates stored state.
        self.persist_watermarks = persist_watermarks
        self.watermark_max_jump_pct = watermark_max_jump_pct
        self.signals: list[TradeSignal] = []

    def _watermarks(self, symbol: str, current_price: float) -> tuple[float, float]:
        """Return ``(high, recent_high)`` — all-time ratchet for stops/profit
        protection and rolling recent high for buy-the-dip."""
        return update_watermarks(
            symbol, current_price,
            persist=self.persist_watermarks,
            max_jump_pct=self.watermark_max_jump_pct,
        )

    def evaluate_all(self) -> list[TradeSignal]:
        """Evaluate all securities and return trade signals."""
        self.signals = []

        for symbol, strategy in self.strategies.items():
            if not strategy.enabled:
                continue

            holding = self.portfolio.holdings.get(symbol)
            current_price = self._get_price(symbol, holding)

            if current_price <= 0:
                continue

            if strategy.mode == StrategyMode.CASH_OUT:
                self._evaluate_cash_out(symbol, holding, strategy, current_price)
            elif strategy.mode == StrategyMode.INCREASE_HOLDING:
                self._evaluate_increase_holding(symbol, holding, strategy, current_price)
            elif strategy.mode == StrategyMode.HOLD:
                self._evaluate_hold(symbol, holding, strategy, current_price)

        # Sort by priority (highest first), then by the configured symbol order
        # (earlier in settings = higher priority). Budget is already reserved in
        # this same symbol order during generation (see _check_guidelines), so a
        # symbol listed first wins ties and gets funded first when budget is tight.
        order = {sym: i for i, sym in enumerate(self.strategies.keys())}
        self.signals.sort(key=lambda s: (-s.priority, order.get(s.symbol, 10**9)))
        return self.signals

    def _get_price(self, symbol: str, holding: Optional[Holding]) -> float:
        """Get current price from fetcher or fall back to holding's last price."""
        if self.price_fetcher:
            price = self.price_fetcher(symbol)
            if price > 0:
                return price
        if holding:
            return holding.last_price
        return 0.0

    # ── CASH-OUT FORK ──────────────────────────────────────────────────

    def _evaluate_cash_out(self, symbol: str, holding: Optional[Holding],
                            strategy: TradingStrategy, current_price: float):
        """Check stop-loss and take-profit triggers."""
        if not holding or holding.quantity <= 0:
            return

        params = strategy.cash_out
        if not params:
            return

        avg_cost = holding.average_cost_basis
        if avg_cost <= 0:
            return

        pct_change = ((current_price - avg_cost) / avg_cost) * 100
        sell_qty = round(holding.quantity * (params.sell_quantity_pct / 100), 4)

        # Take-profit check
        if params.should_take_profit(current_price, avg_cost):
            self.signals.append(TradeSignal(
                symbol=symbol,
                side=OrderSide.SELL,
                quantity=sell_qty,
                reason=f"TAKE-PROFIT triggered ({pct_change:+.1f}% vs target {params.take_profit_pct}%)",
                estimated_value=sell_qty * current_price,
                strategy_mode=StrategyMode.CASH_OUT,
                priority=8,
            ))
            return

        # Trailing stop check — uses the all-time high watermark (ratchet)
        if params.trailing_stop_pct is not None:
            peak, _ = self._watermarks(symbol, current_price)
            pct_from_peak = ((current_price - peak) / peak) * 100 if peak > 0 else 0

            if pct_from_peak <= params.trailing_stop_pct:
                self.signals.append(TradeSignal(
                    symbol=symbol,
                    side=OrderSide.SELL,
                    quantity=sell_qty,
                    reason=(
                        f"TRAILING STOP triggered "
                        f"({pct_from_peak:+.1f}% from peak ${peak:,.2f}, "
                        f"trail: {params.trailing_stop_pct}%)"
                    ),
                    estimated_value=sell_qty * current_price,
                    strategy_mode=StrategyMode.CASH_OUT,
                    priority=9,
                ))

    # ── HOLD FORK ─────────────────────────────────────────────────────

    def _evaluate_hold(self, symbol: str, holding: Optional[Holding],
                       strategy: TradingStrategy, current_price: float):
        """Hold position — only sell if stop-loss triggers."""
        if not holding or holding.quantity <= 0:
            return

        params = strategy.hold
        if not params:
            return

        avg_cost = holding.average_cost_basis
        if avg_cost <= 0:
            return

        if params.should_stop_loss(current_price, avg_cost):
            pct_change = ((current_price - avg_cost) / avg_cost) * 100
            sell_qty = round(holding.quantity * (params.sell_quantity_pct / 100), 4)
            self.signals.append(TradeSignal(
                symbol=symbol,
                side=OrderSide.SELL,
                quantity=sell_qty,
                reason=f"STOP-LOSS triggered ({pct_change:+.1f}% vs limit {params.stop_loss_pct}%)",
                estimated_value=sell_qty * current_price,
                strategy_mode=StrategyMode.HOLD,
                priority=10,
            ))

    # ── INCREASE-HOLDING FORK ──────────────────────────────────────────

    def _evaluate_increase_holding(self, symbol: str, holding: Optional[Holding],
                                     strategy: TradingStrategy, current_price: float):
        """Check take-profit, DCA schedule, and buy-the-dip (watermark-based) triggers."""
        params = strategy.increase_holding
        if not params:
            return

        # Update both peaks once — all-time ``high`` for profit protection, rolling
        # ``recent_high`` for buy-the-dip.
        high, recent_high = self._watermarks(symbol, current_price)

        # Profit protection — sell when price is dropping from the all-time peak
        # while still in profit.
        if holding and holding.quantity > 0 and holding.average_cost_basis > 0:
            if params.should_protect_profit(current_price, holding.average_cost_basis, high):
                current_profit_pct = ((current_price - holding.average_cost_basis) / holding.average_cost_basis) * 100
                pct_from_peak = ((current_price - high) / high) * 100
                sell_qty = round(holding.quantity * (params.sell_quantity_pct / 100), 4)
                self.signals.append(TradeSignal(
                    symbol=symbol,
                    side=OrderSide.SELL,
                    quantity=sell_qty,
                    reason=(
                        f"PROFIT PROTECTION: {pct_from_peak:+.1f}% from peak ${high:,.2f}, "
                        f"locking {current_profit_pct:+.1f}% gain (floor: {params.min_profit_pct}%)"
                    ),
                    estimated_value=sell_qty * current_price,
                    strategy_mode=StrategyMode.INCREASE_HOLDING,
                    priority=8,
                ))

        # DCA check → DCA budget (with timing enforcement)
        dca_due = params.dca_amount > 0
        if dca_due and self.last_dca_dates:
            last_date = self.last_dca_dates.get(symbol)
            if last_date:
                days_since = (date.today() - last_date).days
                if days_since < params.dca_interval_days:
                    dca_due = False

        if dca_due:
            buy_qty = round(params.dca_amount / current_price, 4)
            if self._check_guidelines(params.dca_amount, BuyType.DCA):
                self.signals.append(TradeSignal(
                    symbol=symbol,
                    side=OrderSide.BUY,
                    quantity=buy_qty,
                    reason=f"DCA: ${params.dca_amount:.2f} every {params.dca_interval_days}d",
                    estimated_value=params.dca_amount,
                    strategy_mode=StrategyMode.INCREASE_HOLDING,
                    buy_type=BuyType.DCA,
                    priority=2,
                ))

        # Buy-the-dip check — triggers when price drops from the rolling recent high
        if params.buy_dip_pct < 0 and holding:
            pct_from_peak = ((current_price - recent_high) / recent_high) * 100 if recent_high > 0 else 0

            if pct_from_peak <= params.buy_dip_pct:
                dip_buy_value = params.dca_amount if params.dca_amount > 0 else self.guidelines.strategy.max_single_order
                buy_qty = round(dip_buy_value / current_price, 4)

                if self._check_guidelines(dip_buy_value, BuyType.STRATEGY):
                    self.signals.append(TradeSignal(
                        symbol=symbol,
                        side=OrderSide.BUY,
                        quantity=buy_qty,
                        reason=f"BUY-THE-DIP: {pct_from_peak:+.1f}% from recent high ${recent_high:,.2f} (trigger: {params.buy_dip_pct}%)",
                        estimated_value=dip_buy_value,
                        strategy_mode=StrategyMode.INCREASE_HOLDING,
                        buy_type=BuyType.STRATEGY,
                        priority=5,
                        limit_price=round(current_price, 2),
                    ))

    # ── GUIDELINES CHECK ───────────────────────────────────────────────

    def _check_guidelines(self, amount: float, buy_type: BuyType) -> bool:
        """Check if an investment amount is allowed under the given buy type's budget.

        If allowed, provisionally reserves the amount so that subsequent
        signals in the same evaluation see the reduced headroom.
        """
        allowed, reason = self.guidelines.can_invest(amount, buy_type)
        if not allowed:
            return False

        # Reserve the amount so the next signal sees reduced budget
        self.guidelines.record_investment(amount, buy_type)
        return True


def print_signals(signals: list[TradeSignal]):
    """Print trade signals grouped by buy type."""
    if not signals:
        print("\n  No trade signals generated.")
        return

    sell_signals = [s for s in signals if s.side == OrderSide.SELL]
    dca_signals = [s for s in signals if s.side == OrderSide.BUY and s.buy_type == BuyType.DCA]
    strat_signals = [s for s in signals if s.side == OrderSide.BUY and s.buy_type == BuyType.STRATEGY]

    print(f"\n  {'─'*60}")
    print(f"  TRADE SIGNALS ({len(signals)})")
    print(f"  {'─'*60}")

    if sell_signals:
        print(f"\n  SELL orders:")
        for s in sell_signals:
            print(s)

    if strat_signals:
        print(f"\n  STRATEGY buys (dip):")
        for s in strat_signals:
            print(s)

    if dca_signals:
        print(f"\n  DCA buys (scheduled):")
        for s in dca_signals:
            print(s)

    print(f"\n  {'─'*60}")
    total_sell = sum(s.estimated_value for s in sell_signals)
    total_dca = sum(s.estimated_value for s in dca_signals)
    total_strat = sum(s.estimated_value for s in strat_signals)
    if total_sell > 0:
        print(f"  Total sells:         ${total_sell:>10,.2f}")
    if total_strat > 0:
        print(f"  Total strategy buys: ${total_strat:>10,.2f}")
    if total_dca > 0:
        print(f"  Total DCA buys:      ${total_dca:>10,.2f}")
    print()
